### ISSUE TITLE
Show required flag for an API during Developer Trial

### ISSUE THREAD

**Issue by christianliebel** [GoogleChromeLabs/fugu-tracker#5]
**Is your feature request related to a problem? Please describe.**

It would be helpful if the tracker could show the exact flag you need to enable to use a new API during its Developer Trial. Otherwise, you need to find the related web.dev article (if any) and look up the flag there.

**Describe the solution you'd like**

I would suggest adding the required flag to the flag tag's tooltip.

![Possible implementation](https://user-images.githubusercontent.com/6698344/106353694-b0073b80-62ec-11eb-814d-482662fe1efb.png)

**Describe alternatives you've considered**

The flag could alternatively be shown in the capability's details pane or included in the yellow flag tag.

**Additional context**

It may make sense to add this information to chromestatus.com (see https://github.com/GoogleChrome/chromium-dashboard/issues/857) and display it here accordingly.

**Comment by Snugug** [comment]
Thanks for the feedback here! I totally agree that it'd be great to show the flag here. In order to do that, as you suggested, this information should be added as a specific field to Chrome Status (or CRBug) and, once added, we can pull it and display it. Until then, I think we may need to wait on implementing this as one of the goals of this particular tracker isn't to own information about any of the items being tracked itself, but rather to display existing information, in order to ensure data is up-to-date with the tools teams are already using to maintain their feature launches.

**Comment by Snugug** [comment]
This now appears available from Chrome Status as `flag_name` and can be parsed
